pupsite/pups/forms/add_pup.py
from flask_wtf import FlaskForm
from wtforms import (SubmitField, StringField, IntegerField, TextAreaField, FileField)
from wtforms.validators import Length, NumberRange, DataRequired

from pupsite.utils.picture_utils import validate_picture_format


class AddPupForm(FlaskForm):
    """
    Form for creating a Pup
    """
    name = StringField(label="Name", validators=[Length(min=3, max=20), DataRequired()])
    breed = StringField(label="Breed", validators=[Length(min=3, max=20), DataRequired()])
    age = IntegerField(label="Age", validators=[NumberRange(min=1, max=20), DataRequired()])
    details = TextAreaField(label="Details", validators=[DataRequired()])
    picture = FileField(label="Picture", validators=[validate_picture_format])
    submit = SubmitField(label="Add Pup")

pupsite/pups/forms/pup_update.py
from flask_wtf import FlaskForm
from wtforms import (SubmitField, StringField, IntegerField, TextAreaField, FileField)
from wtforms.validators import Length, NumberRange


class UpdatePupForm(FlaskForm):
    """
    Form for creating a Pup
    """
    breed = StringField(label="Breed", validators=[Length(min=3, max=20)])
    age = IntegerField(label="Age", validators=[NumberRange(min=1, max=20)])
    details = TextAreaField(label="Details")
    picture = FileField(label="Picture", validators=[])
    update = SubmitField(label="Update Pup")

pupsite/pups/__init__.py
from .routes.pups_list import pups_list
from .routes.add_pup import add_pup
from .routes.delete_pup import delete_pup
from .routes.pup_page import pup_page
from .routes.pup_update import update_pup

pupsite/pups/routes/__init__.py
import os
from flask import Blueprint

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
TEMPLATES_FOLDER = os.path.join(BASE_DIR, "templates")
pupsblueprint = Blueprint("pupsblueprint", __name__, template_folder=TEMPLATES_FOLDER)

pupsite/pups/routes/add_pup.py
from flask import redirect, url_for, render_template, flash
from flask_login import login_required, current_user

from pupsite import db
from pupsite.models import Pup
from pupsite.pups.forms.add_pup import AddPupForm
from pupsite.pups.routes import pupsblueprint

from pupsite.utils.picture_utils import save_picture_by_dimensions


@pupsblueprint.route("/pup/add", methods=["GET", "POST"])
@login_required
def add_pup():
    """
    Route for creating a new Pup connection with the owner
    """
    form = AddPupForm()
    if form.validate_on_submit():
        picture = "default.png"
        if form.picture.data:
            picture = save_picture_by_dimensions(form.picture.data)
        pup = Pup(
            name=form.name.data,
            breed=form.breed.data,
            age=form.age.data,
            details=form.details.data,
            owner_id=current_user.id,
            picture=picture
        )
        db.session.add(pup)
        db.session.commit()
        flash("Pup Added Successfully", category="success")
        return redirect(url_for("pupsblueprint.pups_list"))
    return render_template("add_pup.html", title="add a pup", add_form=form)

pupsite/pups/routes/delete_pup.py
from flask import redirect, url_for, flash, abort
from flask_login import current_user, login_required

from pupsite import db
from pupsite.models import Pup
from pupsite.pups.routes import pupsblueprint


@pupsblueprint.route("/pup/<int:pup_id>/delete", methods=["GET", "POST"])
@login_required
def delete_pup(pup_id):
    """
    Route for Deleting a Pup from the database
    """

    pup = db.get_or_404(Pup, pup_id)
    if pup.owner_id != current_user.id:
        flash("Action forbidden. You can't delete someone else's pup. ")
        return abort(403)
    db.session.delete(pup)
    db.session.commit()
    flash(f"You Successfully Deleted the Pup called {pup.name}", category="success")
    return redirect(url_for("pupsblueprint.pups_list"))

pupsite/pups/routes/pup_page.py
from flask import render_template, url_for

from pupsite import db
from pupsite.models import Pup
from pupsite.pups.routes import pupsblueprint


@pupsblueprint.route("/pups/<int:pup_id>", methods=["GET"])
def pup_page(pup_id):
    """
    Show information about a particular pup

    Args:
        pup_id(int) : The primary key of the given Pup
    """
    pup = db.get_or_404(Pup, pup_id)
    return render_template("pup_page.html", title=f"{pup.name}", pup=pup)

pupsite/pups/routes/pup_update.py
from flask import render_template, redirect, flash, abort, url_for, request
from flask_login import login_required, current_user

from pupsite import db
from pupsite.models import Pup
from pupsite.pups.forms.pup_update import UpdatePupForm
from pupsite.pups.routes import pupsblueprint
from pupsite.utils.picture_utils import save_picture_by_dimensions


@pupsblueprint.route("/pup/<int:pup_id>/update", methods=["GET", "POST"])
@login_required
def update_pup(pup_id):
    """
    Route to update details about a particular pup given by the pup_id
    Ensure Only the owner of the pup can update details about the pup
    Args:
        pup_id (int): The primary key of the pup to be updated

    Returns:
        response : Returns Http response
    """
    update_form = UpdatePupForm()
    pup = db.get_or_404(Pup, pup_id)

    if current_user.id != pup.owner_id:
        flash("Forbidden! You can only update your own Pup", category="danger")
        return abort(403)
    if update_form.validate_on_submit():
        if update_form.picture.data:
            pup.picture = save_picture_by_dimensions(update_form.picture.data)
        pup.breed = update_form.breed.data
        pup.details = update_form.details.data
        pup.age = update_form.age.data
        db.session.commit()
        return redirect(url_for("pupsblueprint.pups_list"))
    elif request.method == "GET":
        update_form.breed.data = pup.breed
        update_form.details.data = pup.details
        update_form.age.data = pup.age
    return render_template("update_pup.html", update_form=update_form, pup=pup)

pupsite/pups/routes/pups_list.py
from flask import render_template

from pupsite import db
from pupsite.models import Pup
from pupsite.pups.routes import pupsblueprint


@pupsblueprint.route("/pups", methods=["GET"])
def pups_list():
    """
    Lists all the pupsblueprint in the database

    Returns:
        list :A list of all the pupsblueprint in the database
    """
    pups = db.session.execute(db.select(Pup)).scalars()
    return render_template("pupslist.html", title="Pups", pups=pups)

pupsite/pups/templates/add_pup.html
{% extends "base.html" %}
{% set active_page = 'add_pup' %}
{% block body %}
    <div class="container">
        <article class="page-article mt-10">

            <form action="" method="POST" enctype="multipart/form-data">
                {{ add_form.hidden_tag() }}
                <fieldset>
                    <legend class="text-center mt-2">Create a New Pup</legend>
                    <div class="form-group mb-3">
                        {{ add_form.name.label(class="col-sm-2 col-form-label") }}
                        {% if add_form.name.errors %}
                            {{ add_form.name(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in add_form.name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ add_form.name(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ add_form.breed.label(class="col-sm-2 col-form-label") }}
                        {% if add_form.breed.errors %}
                            {{ add_form.breed(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in add_form.breed.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ add_form.breed(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ add_form.age.label(class="col-sm-2 col-form-label") }}
                        {% if add_form.age.errors %}
                            {{ add_form.age(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in add_form.age.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ add_form.age(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>
                    <div class="form-outline-mb4 form-group">
                        {{ add_form.details.label(class="col-sm-2 col-form-label") }}
                        {% if add_form.details.erors %}
                            {{ add_form.details(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in add_form.details.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ add_form.details(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>
                    <div class="form-outline-mb4 form-group">
                        {{ add_form.picture.label(class="col-sm-2 col-form-label") }}
                        {% if add_form.picture.errors %}
                            {{ add_form.picture(class="form-control-file is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in add_form.picture.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ add_form.picture(class="form-control-file") }}
                        {% endif %}
                    </div>
                    {{ add_form.submit(class="btn btn-primary mt-2 mb-2") }}
                </fieldset>
            </form>
        </article>
    </div>
{% endblock body %}

pupsite/pups/templates/pup_page.html
{% extends "base.html" %}
{% set active_page= 'pup_page' %}
{% block body %}
    <div class="container">
        <article class="page-article">
            <h1>{{ pup.name }}</h1>

            <div class="card mb-2">
                <h5 class="card-header text-center">{{ pup.name or "Bingo" }}</h5>
                <div class="card-body">
                    <h5 class="card-title">{{ pup.breed or "German Shepherd" }}</h5>
                    <div class="row">
                        <div class="col-8">
                            <p class="card-text">{{ pup.details }}</p>
                        </div>
                        <div class="col">
                            <img class="col-4 img-thumbnail rounded-circle"
                                 src="{{ url_for('static', filename='images/' + pup.picture) }}"
                                 alt="puppy image"/>
                        </div>
                    </div>
                    <a href="{{ url_for('pupsblueprint.update_pup', pup_id=pup.id) }}"
                       class="btn btn-secondary">
                        Update Details
                    </a>
                    <button class="btn btn-danger"
                            data-bs-toggle="modal" data-bs-target="#deletePupModal">Delete This Pup
                    </button>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="deletePupModal" tabindex="-1"
                 aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to
                                Delete This
                                Pup?</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <img class="rounded-circle"
                                 src="{{ url_for('static', filename='images/sad_pup.jpg') }}"
                                 alt="sad puppy"/>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                Close
                            </button>
                            <form action="{{ url_for('pupsblueprint.delete_pup', pup_id=pup.id) }}"
                                  method="POST">
                                <input class="btn btn-danger" type="submit" value="Save Changes"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </div>
{% endblock body %}

pupsite/pups/templates/pupslist.html
{% extends "base.html" %}
{% set active_page = 'pups_list' %}
{% block body %}
    <div class="container">
        <article class="page-article">
            <h1>Pups List</h1>
            {% for pup in pups %}
                <div class="card mb-2">
                    <h5 class="card-header text-center">{{ pup.name or "Bingo" }}</h5>
                    <div class="card-body">
                        <h5 class="card-title">{{ pup.breed or "German Shepherd" }}</h5>
                        <p class="card-text">{{ pup.details }}</p>
                        <a href="{{ url_for('pupsblueprint.pup_page', pup_id=pup.id) }}"
                           class="btn btn-secondary">
                            More Details
                        </a>
                        <button class="btn btn-danger"
                                data-bs-toggle="modal" data-bs-target="#deletePupModal">Delete This
                            Pup
                        </button>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="deletePupModal" tabindex="-1"
                     aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want
                                    to Delete This
                                    Pup?</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <img class=""
                                     src="{{ url_for('static', filename='images/sad_pup.jpg') }}"
                                     alt="sad puppy"/>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close
                                </button>
                                <form action="{{ url_for('pupsblueprint.delete_pup', pup_id=pup.id) }}"
                                      method="POST">
                                    <input class="btn btn-danger" type="submit"
                                           value="Save Changes"/>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </article>
    </div>
{% endblock body %}

pupsite/pups/templates/update_pup.html
{% extends "base.html" %}
{% set active_page = 'update_pup' %}
{% block body %}
    <div class="container">
        <article class="page-article mt-10">

            <form action="" method="POST" enctype="multipart/form-data">
                {{ update_form.hidden_tag() }}
                <fieldset>
                    <legend class="text-center mt-2">Update {{ pup.name }}</legend>

                    <div class="form-group">
                        {{ update_form.breed.label(class="col-sm-2 col-form-label") }}
                        {% if update_form.breed.errors %}
                            {{ update_form.breed(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in update_form.breed.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ update_form.breed(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ update_form.age.label(class="col-sm-2 col-form-label") }}
                        {% if update_form.age.errors %}
                            {{ update_form.age(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in update_form.age.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ update_form.age(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>
                    <div class="form-outline-mb4 form-group">
                        {{ update_form.details.label(class="col-sm-2 col-form-label") }}
                        {% if update_form.details.erors %}
                            {{ update_form.details(class="form-control form-control-md col col-lg-2 is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in update_form.details.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ update_form.details(class="form-control form-control-md col col-lg-2") }}
                        {% endif %}
                    </div>
                    <div class="form-outline-mb4 form-group">
                        {{ update_form.picture.label(class="col-sm-2 col-form-label") }}
                        {% if update_form.picture.errors %}
                            {{ update_form.picture(class="form-control-file is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in update_form.picture.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ update_form.picture(class="form-control-file") }}
                        {% endif %}
                    </div>
                    {{ update_form.update(class="btn btn-primary mt-2 mb-2") }}
                </fieldset>
            </form>
        </article>
    </div>
{% endblock body %}